apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: elixir-library
  title: Elixir Library
  description:
    Generic boilerplate for a Mix library
  tags:
    - recommended
    - elixir
    - library
spec:
  owner: team-baemax
  templater: cookiecutter
  type: library
  path: '.'
  schema:
    required:
      - otp_app
      - module_name
      - description
      - private
    properties:
      otp_app:
        title: OTP Application Name
        type: string
        description: >-
          The Elixir OTP application name. Should be snake_case. For Haste
          this is "haste".
      module_name:
        title: Module Name
        type: string
        description: >-
          The Elixir module name to use. Should be PascalCase. For Haste this
          is "Haste".
      description:
        title: Description
        type: string
        description: >-
          A brief description of the library. Around 40-80 characters will do.
      private:
        title: Private Library?
        description: >-
          Is this library for internal use only? Private libraries will be
          configured to publish to our private Hex and use extra internal
          dependencies like convene.
        type: string
        enum:
          - "y"
          - "n"
        default: "y"
